create extension if not exists pgcrypto;

create table if not exists public.installs (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  source text not null check (source in ('appinstalled', 'standalone_launch')),
  installed_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.installs enable row level security;

create policy "public_can_insert_installs_once"
on public.installs
for insert
to anon
with check (
  source in ('appinstalled', 'standalone_launch')
  and length(device_id) > 0
);

create or replace function public.get_installs_count()
returns integer
language sql
security definer
set search_path = public
as $$
  select count(*)::integer from public.installs;
$$;

grant execute on function public.get_installs_count() to anon;
revoke all on public.installs from anon;
grant insert on public.installs to anon;
